//// Generated by CoffeeScript 1.7.1
//(function() {
//  var expect, tags;
//
//  expect = require('chai').expect;
//
//  tags = require('../lib/tags.coffee');
//
//  console.log(a);
//
//  describe('Tags', function() {
//    return describe('#pase()', function() {
//      return it('should parse long formed tags', function() {
//        var args, results;
//        console.log();
//        args = ['--depth=4', '--hello=world'];
//        results = tags.parse(args);
//        expect(results).to.have.a.property('depth', 4);
//        return expect(results).to.have.a.property('hello', 'world');
//      });
//    });
//  });
//
//}).call(this);
