// Generated by CoffeeScript 1.7.1
(function() {
  var exports;

  exports = module.exports = {};

  exports.parse = function() {
    var options;
    options = {};
    return options;
  };

}).call(this);
